In [ ]:
a = [[1.5, 2.5], [3.0, 4.0]]
b = [2, 1]

In [ ]:

import numpy as np
b = np.array(b)
a = np.array(a)
if b.ndim == 1:
    b = b.reshape(1,-1)
b_t = b.T

In [ ]:
a_row, a_col = a.shape[0], a.shape[1]

b_row, b_col = b_t.shape[0], b_t.shape[1]

if a_col != b_row:
    print(-1)

In [ ]:
print(np.matmul(a,b_t).tolist())

In [ ]:
res_mat = [[0]*b_col for _ in range(a_row)]

for row in range(a_row):
    for col in range(b_col):
        

In [ ]:
res_mat = [[0]*b_col for _ in range(a_row)]

In [ ]:
res_mat

In [ ]:
a = [1, 2, 3], [4, 5, 6]



In [ ]:
[row for row in zip(*a)]

In [ ]:
matrix = [[2, 1], [1, 2]]
A = np.array(matrix)
eigenvalues, eigenvectors = np.linalg.eig(A)

In [ ]:
eigenvalues

In [ ]:
from sympy import symbols, Matrix

lam = symbols('λ')
id_matrix = lam*id_matrix

In [ ]:
diff_matrix = matrix-id_matrix

In [ ]:
diff_matrix

In [ ]:
A = [[1, 2], [3, 4]]
T = [[2, 0], [0, 2]]
S = [[1, 1], [0, 1]]

A = np.array(A)
T = np.array(T)
S = np.array(S)
t_inv = np.linalg.inv(T)

t_a = np.matmul(t_inv, A)
print(np.matmul(t_a, S))

In [ ]:
matrix = [[4, 7], [2, 6]]
a,b = matrix[0]
c,d = matrix[1]

det = a*d-b*c

result = [[d/det, -c/det], [-b/det, a/det]]

In [ ]:
result

In [ ]:
A = [[5, -2, 3], [-3, 9, 1], [2, -1, -7]]
b = [-1, 2, 3]
n=2
n = len(A)
x = [0.0] * n  

for _ in range(n):
    x_new = x.copy()
    for i in range(n):
        s = sum(A[i][j] * x[j] for j in range(n) if j != i)
        x_new[i] = round((b[i] - s) / A[i][i], 4)
    x = x_new

In [ ]:
x

In [189]:
X = [[1, 1], [1, 2], [1, 3]]
y = [1, 2, 3]
X = np.array(X)
y = np.array(y)
y = y.reshape(-1,1)
W = np.random.rand(X.shape[1], 1)
lr =0.1



In [190]:
for i in range(200):
    pred = np.matmul(X,W)
    x_t = X.T
    derivative = (np.matmul(x_t, pred-y))
    #print(derivative.shape)
    W = W - lr*(derivative)
    

W


array([[2.96466352e-04],
       [9.99869584e-01]])

In [191]:
print(np.round(W, 2))

[[0.]
 [1.]]


In [167]:
a = y.reshape(-1,4)
a.shape

(1, 4)

In [192]:
num = 0.2
nums_list = [num]*10

print(sum(nums_list))

1.9999999999999998


In [194]:
import numpy as np
print(numpy.sum(nums_list))

2.0


In [195]:
np.sqrt(2/3)

0.816496580927726

In [196]:
0.816496580927726*2

1.632993161855452

In [206]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data[:][:1]

array([[1, 2]])

In [211]:
col1 = data[:, 0]
col2 = data[:, 1]

In [213]:
col2

array([2, 4, 6])

In [214]:
col1_mean, col2_mean = np.mean(col1), np.mean(col2)
col1_std, col2_std = np.std(col1), np.std(col2)
n = data.shape[0]

col1_min, col2_min = np.min(col1), np.min(col2)
col1_maxx, col2_max = np.max(col1), np.max(col2)

In [233]:
a1,b1 = (col1-col1_min)/(col1_maxx-col1_min), (col2-col2_min)/(col2_max-col2_min)
a1,b1 = a1.reshape(-1,1), b1.reshape(-1,1)
standardized_data = np.concatenate((a1,b1), axis =1)

In [234]:
c1,d1 = (col1-col1_mean)/(col1_std), (col2-col2_mean)/(col2_std)
c1,d1 = c1.reshape(-1,1), d1.reshape(-1,1)
standardized_data = np.concatenate((c1,d1), axis =1)

array([[0. , 0. ],
       [0.5, 0.5],
       [1. , 1. ]])

In [231]:
b1.shape

(3,)

In [237]:
B = [[1, 0, 0], 
             [0, 1, 0], 
             [0, 0, 1]]
C = [[1, 2.3, 3], 
             [4.4, 25, 6], 
             [7.4, 8, 9]]

c = np.array(C)
print(np.linalg.inv(c))

[[-0.67722681 -0.01262626  0.23415978]
 [-0.01836547  0.05050505 -0.02754821]
 [ 0.5731558  -0.03451178 -0.05693297]]


In [241]:
data = np.array([[1, 2], [3, 4], [5, 6]])
k = 1
X_mean = data-np.mean(data, axis =0)
cov_matrix = np.cov(X_mean, rowvar = False)
eigenvalues, eigenvectors = np.linalg.eigh(cov_matrix)
sorted_indices = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[sorted_indices]
eigenvectors = eigenvectors[:, sorted_indices]
eigen_subvectors = eigenvectors[:, :2]
principal_components = np.dot(X_mean, eigen_subvectors)



In [240]:
sorted_indices

array([8., 0.])

In [242]:
principal_components

array([[-2.82842712,  0.        ],
       [ 0.        ,  0.        ],
       [ 2.82842712,  0.        ]])

In [243]:
eigen_subvectors

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [252]:
features = [[1.0, 2.0], [2.0, 1.0], [-1.0, -2.0]]
labels = [1, 0, 0]
initial_weights = [0.1, -0.2]
initial_bias = 0.0
learning_rate = 0.1
epochs = 2

import numpy as np

def sigmoid_fn(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sig = sigmoid_fn(x)
    return sig * (1 - sig)

def train_single_neuron(features, labels, initial_weights, initial_bias, learning_rate, epochs):
    features = np.array(features)
    labels = np.array(labels)
    weights = np.array(initial_weights, dtype=np.float64)
    bias = float(initial_bias)
    mse_values = []

    for epoch in range(epochs):
        # Forward pass
        linear_output = np.dot(features, weights) + bias
        predictions = sigmoid_fn(linear_output)

        # Error and MSE
        error = labels - predictions
        mse = np.mean(error ** 2)
        mse_values.append(round(mse, 4))

        # Gradients
        d_pred = error * sigmoid_derivative(linear_output)  # shape: (n_samples,)
        weights_grad = np.dot(features.T, d_pred) / len(features)  # shape: (n_features,)
        bias_grad = np.mean(d_pred)

        # Update
        weights += learning_rate * weights_grad
        bias += learning_rate * bias_grad

    updated_weights = [round(w, 4) for w in weights]
    updated_bias = round(bias, 4)

    return updated_weights, updated_bias, mse_values


In [256]:
features = [[1.0, 2.0], [2.0, 1.0], [-1.0, -2.0]]
labels = [1, 0, 0]
initial_weights = [0.1, -0.2]
initial_bias = 0.0
learning_rate = 0.1
epochs = 4000

updated_weights, updated_bias, mse_values = train_single_neuron(
    features, labels, initial_weights, initial_bias, learning_rate, epochs
)

print("Updated weights:", updated_weights)
print("Updated bias:", updated_bias)
#print("MSE per epoch:", mse_values)


Updated weights: [-2.3346, 2.8813]
Updated bias: -0.8117


In [257]:
class Value:
	def __init__(self, data, _children=(), _op=''):
		self.data = data
		self.grad = 0
		self._backward = lambda: None
		self._prev = set(_children)
		self._op = _op
	def __repr__(self):
		return f"Value(data={self.data}, grad={self.grad})"

	def __add__(self, other):
		 # Implement addition here
		pass

	def __mul__(self, other):
		# Implement multiplication here
		pass

	def relu(self):
		# Implement ReLU here
		pass

	def backward(self):
		# Implement backward pass here
		pass

In [258]:
A = [[-10, 8], 
         [10, -1]]
A = np.array(A)
u,s,v = np.linalg.svd(A)

In [259]:
u,s,v

(array([[-0.8,  0.6],
        [ 0.6,  0.8]]),
 array([15.65247584,  4.47213595]),
 array([[ 0.89442719, -0.4472136 ],
        [ 0.4472136 ,  0.89442719]]))

In [266]:
X = np.array([[1, 2], 
                  [3, 4], 
                  [5, 6], 
                  [7, 8]])
y = np.array([1, 2, 3, 4])

seed = np.random.seed(42)
rand_indices = np.random.randint(1, X.shape[0])

In [293]:
X = np.array([[1, 2], 
                  [3, 4], 
                  [5, 6], 
                  [7, 8], 
                  [9, 10]])
y = np.array([1, 2, 3, 4, 5])
batch_size = 2
#batch_iterator(X, y, batch_size)

In [294]:
#y = y.reshape(-1,1)

In [295]:
X.shape, y.shape

((5, 2), (5,))

In [296]:
sample = np.concatenate((X, y), axis = 1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [297]:
result = []
for i in range(0, X.shape[0], batch_size):  # step by batch_size
    X_batch = X[i:i+batch_size].tolist()
    y_batch = y[i:i+batch_size].tolist()
    result.append([X_batch, y_batch])

In [298]:
result

[[[[1, 2], [3, 4]], [1, 2]], [[[5, 6], [7, 8]], [3, 4]], [[[9, 10]], [5]]]

In [288]:
y[0:batch_size]

array([[1],
       [2]])

In [289]:
y

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [308]:
X = np.array([[1, 2], 
                  [3, 4], 
                  [5, 6], 
                  [7, 8], 
                  [9, 10]])
feature_i = 0
threshold = 5

print(X[X[:, feature_i] >= threshold])

[[ 5  6]
 [ 7  8]
 [ 9 10]]


In [326]:
queries = [[0,1],[0,3],[2,4],[3,4],[2,2]]


heights = [6,4,8,5,2,7]
size_h = len(heights)
n = len(queries)
result = [-1]*n

for i, (x,y) in enumerate(queries):
    print(f"Index : {i} and x : {x}, {heights[x]} and y : {y}, {heights[y]}")
    if heights[x] == heights[y]:
        result[i] = x 
    elif (x<y) and  heights[x] < heights[y]:
        result[i] = y
    elif (x>y) or heights[x] > heights[y]:
        max_index = max(x,y)
        print(f"Max index is {max_index}")
        for k in range(max_index+1, size_h):
            print(f"K ; {k}")
            if (heights[k] > heights[x]) and (heights[k] > heights[y]):
                result[i] = k
                print(f"result list is {result}")
                break
    else:
        pass

Index : 0 and x : 0, 6 and y : 1, 4
Max index is 1
K ; 2
result list is [2, -1, -1, -1, -1]
Index : 1 and x : 0, 6 and y : 3, 5
Max index is 3
K ; 4
K ; 5
result list is [2, 5, -1, -1, -1]
Index : 2 and x : 2, 8 and y : 4, 2
Max index is 4
K ; 5
Index : 3 and x : 3, 5 and y : 4, 2
Max index is 4
K ; 5
result list is [2, 5, -1, 5, -1]
Index : 4 and x : 2, 8 and y : 2, 8


In [328]:
heights = [5,3,8,2,6,1,4,6]
queries = [[0,7],[3,5],[5,2],[3,0],[1,6]]
size_h = len(heights)
n = len(queries)
result = [-1]*n

for i, (x,y) in enumerate(queries):
    print(f"Index : {i} and x : {x}, {heights[x]} and y : {y}, {heights[y]}")
    if heights[x] == heights[y]:
        result[i] = x 
    elif (x<y) and  heights[x] < heights[y]:
        result[i] = y
    elif (x>y) or heights[x] > heights[y]:
        max_index = max(x,y)
        print(f"Max index is {max_index}")
        for k in range(max_index+1, size_h):
            print(f"K ; {k}")
            if (heights[k] > heights[x]) and (heights[k] > heights[y]):
                result[i] = k
                print(f"result list is {result}")
                break
    else:
        pass

Index : 0 and x : 0, 5 and y : 7, 6
Index : 1 and x : 3, 2 and y : 5, 1
Max index is 5
K ; 6
result list is [7, 6, -1, -1, -1]
Index : 2 and x : 5, 1 and y : 2, 8
Max index is 5
K ; 6
K ; 7
Index : 3 and x : 3, 2 and y : 0, 5
Max index is 3
K ; 4
result list is [7, 6, -1, 4, -1]
Index : 4 and x : 1, 3 and y : 6, 4


In [329]:
result

[7, 6, -1, 4, 6]